spring:
  sql:
    init:
      schema-locations: classpath*:db/h2/schema.sql   // (1)
      data-locations: classpath*:db/h2/data.sql       // (2)
logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG